# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbf9a6e66bc276855a378703049342ba77d1299f0ec65b55357b27d16b5e4acf29858b9bb768ff2cbf73225eeb770e96e41bef70d979544d1721ca2d720ddd1b

test:
  secret_key_base: 3f41bb40ba8a9b2076a759a20932c30c1d8b7232f72782bcb990007f08fa8b9279b6b983d968630c38906f85d7708149791edb082a889deecde6cd6e7a34aea5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
